<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	
	<!-- Global packages (private, build-time packages for all projects) -->
	<ItemGroup>
		<GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.9.50" />
		<GlobalPackageReference Include="Umbraco.GitVersioning.Extensions" Version="0.2.0" />
		<GlobalPackageReference Include="Umbraco.JsonSchema.Extensions" Version="0.3.0" />
	</ItemGroup>
	
	<!-- Umbraco packages -->
	<ItemGroup>
		<PackageVersion Include="Umbraco.Cms.Api.Common" Version="17.2.0" />
		<PackageVersion Include="Umbraco.Cms.DevelopmentMode.Backoffice" Version="17.2.1" />
    <PackageVersion Include="Umbraco.Cms.Web.Common" Version="17.2.0" />
    <PackageVersion Include="Umbraco.Cms.Api.Management" Version="17.2.0" />
  </ItemGroup>
</Project>
