<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <Compile Remove="Views\**" />
    <Content Remove="Views\**" />
    <EmbeddedResource Remove="Views\**" />
    <None Remove="Views\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.DevelopmentMode.Backoffice" />
    <PackageReference Include="Umbraco.TheStarterKit" VersionOverride="17.0.0" />
    <PackageReference Include="Umbraco.Cms" VersionOverride="17.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Blip\Blip.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Opt-in to app-local ICU to ensure consistent globalization APIs across different platforms -->
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" VersionOverride="72.1.0.3" />
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="72.1.0.3" Condition="$(RuntimeIdentifier.StartsWith('linux')) or $(RuntimeIdentifier.StartsWith('win')) or ('$(RuntimeIdentifier)' == '' and !$([MSBuild]::IsOSPlatform('osx')))" />
  </ItemGroup>
  
  <PropertyGroup>
    <!-- Razor files are needed for the backoffice to work correctly -->
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
  </PropertyGroup>
</Project>
