<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <PackageId>Blip.Umbraco</PackageId>
    <Title>Blip</Title>
    <Description>Block List item picker for Umbraco CMS</Description>
    <PackageTags>umbraco umbraco-cms umbraco-marketplace</PackageTags>
    <IncludeSymbols>false</IncludeSymbols>
    <StaticWebAssetBasePath>App_Plugins/Blip</StaticWebAssetBasePath>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Web.Common"></PackageReference>
    <PackageReference Include="Umbraco.Cms.Api.Management"></PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Client\generated\" />
  </ItemGroup>
</Project>
